<a href="https://colab.research.google.com/github/luis-jaramillo-talentotech/Talento_Tech_Analisis_de_datos_Basico/blob/main/Laboratorio_9_Parte_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Se tiene un conjunto de datos sobre empleados que incluye su nombre, edad, salario y fecha de ingreso. Se requiere implementar algunos pasos de aseguramiento de la calidad de los datos, como la verificación de valores faltantes y la validación de formatos de datos.
1.	Identificar y contar los valores faltantes en cada columna.
2.	Verificar el formato de la columna 'Salario' para asegurar que todos los valores sean numéricos.
3.	Validar y estandarizar el formato de la columna 'Fecha Ingreso' a YYYY-MM-DD.

In [71]:
import pandas as pd
import numpy as np

data = {
    'Nombre': ['Juan' , 'Ana' , 'Pedro' , 'María' , 'Luis' , 'Ana'],
    'Edad': [28, 34, None, 45, 38, 34],
    'Salario': ['3000', '4000', 'cinco mil', '4500', '4000', '5000' ],
    'FechaIngreso': ['2021-01-15' , '2020/03/12' , '2022-07-01' , '2021/12/01' , '2021-05-20', '2020-03-12']
}

df = pd.DataFrame(data)
print("Información completa:")
print(df)

# Retirar registros repetidos y arreglar índices
df = df.drop_duplicates('Nombre', keep='last')
df = df.reset_index(drop=True)
print("\nTabla sin nombres repetidos e índices corregidos:")
print(df)

# 1.	Identificar y contar los valores faltantes en cada columna.
valores_faltantes = df.isnull().sum()
print("\nValores faltantes por columna:")
print(valores_faltantes)

# Reemplazar 'NaN' en 'Edad' por la media de edades
df['Edad'] = df['Edad'].fillna(df['Edad'].mean())
print("\nTabla con valores de edad inválidos reemplazados por la media:")
print(df)

# 2.	Verificar el formato de la columna 'Salario' para asegurar que todos los valores sean numéricos.
salarios_incorrectos = df[~df['Salario'].str.replace('[^0-9]', '', regex=True).fillna('').str.isdigit()]
print("\nSalarios con formato incorrecto:")
print(salarios_incorrectos)

# Retirar los registros 'salarios incorrectos' del df y arreglar índices
df = df.drop(index = salarios_incorrectos.index)
df = df.reset_index(drop=True)
print("\nTabla sin salarios incorrectos e índices corregidos:")
print(df)

# Convertir 'Salario' en columna numérica
df['Salario'] = df['Salario'].astype(np.float64) # Puede usarse también .astype(int)
print('\nTabla con salarios numéricos:')
print(df)

# 3.	Validar y estandarizar el formato de la columna 'Fecha Ingreso' a YYYY-MM-DD.
df['FechaIngreso'] = df['FechaIngreso'].str.replace('/', '-')
df['FechaIngreso'] = pd.to_datetime(df['FechaIngreso'], errors='coerce', format='%Y-%m-%d')
print("\nDatos después de estandarizar 'FechaIngreso':")
print(df[['Nombre', 'FechaIngreso']])

Información completa:
  Nombre  Edad    Salario FechaIngreso
0   Juan  28.0       3000   2021-01-15
1    Ana  34.0       4000   2020/03/12
2  Pedro   NaN  cinco mil   2022-07-01
3  María  45.0       4500   2021/12/01
4   Luis  38.0       4000   2021-05-20
5    Ana  34.0       5000   2020-03-12

Tabla sin nombres repetidos e índices corregidos:
  Nombre  Edad    Salario FechaIngreso
0   Juan  28.0       3000   2021-01-15
1  Pedro   NaN  cinco mil   2022-07-01
2  María  45.0       4500   2021/12/01
3   Luis  38.0       4000   2021-05-20
4    Ana  34.0       5000   2020-03-12

Valores faltantes por columna:
Nombre          0
Edad            1
Salario         0
FechaIngreso    0
dtype: int64

Tabla con valores de edad inválidos reemplazados por la media:
  Nombre   Edad    Salario FechaIngreso
0   Juan  28.00       3000   2021-01-15
1  Pedro  36.25  cinco mil   2022-07-01
2  María  45.00       4500   2021/12/01
3   Luis  38.00       4000   2021-05-20
4    Ana  34.00       5000   2020-03-12

Salarios con formato incorrecto:
  Nombre   Edad    Salario FechaIngreso
1  Pedro  36.25  cinco mil   2022-07-01

Tabla sin salarios incorrectos e índices corregidos:
  Nombre  Edad Salario FechaIngreso
0   Juan  28.0    3000   2021-01-15
1  María  45.0    4500   2021/12/01
2   Luis  38.0    4000   2021-05-20
3    Ana  34.0    5000   2020-03-12

Tabla con salarios numéricos:
  Nombre  Edad  Salario FechaIngreso
0   Juan  28.0   3000.0   2021-01-15
1  María  45.0   4500.0   2021/12/01
2   Luis  38.0   4000.0   2021-05-20
3    Ana  34.0   5000.0   2020-03-12

Datos después de estandarizar 'FechaIngreso':
  Nombre FechaIngreso
0   Juan   2021-01-15
1  María   2021-12-01
2   Luis   2021-05-20
3    Ana   2020-03-12

Se tiene un conjunto de datos sobre empleados que incluye su nombre, edad, salario, puesto de trabajo y fecha de ingreso. Se requiere implementar aseguramiento de la calidad de los datos, verificando la completitud de los datos, la validez de los salarios y la consistencia de las fechas de ingreso.
1.	Identificar y contar los valores faltantes en cada columna.
2.	Verificar el formato de la columna "Salario" para asegurarse de que todos los valores sean numéricos.
3.	Validar y estandarizar el formato de la columna "FechaIngreso" a YYYY-MM-DD.
4.	Verificar que no haya valores faltantes en la columna "Cargo".

In [93]:
import pandas as pd
import numpy as np

data = {
    'Nombre': ['Juan' , 'Ana' , 'Pedro' , 'María' , 'Luis' , 'Carla '],
    'Edad': [28, None, 40, 45, 38, 34],
    'Salario': ['3000', '4000', '4500', 'cuatro mil', '5000' , '4000'],
    'Cargo' : ['Analista' , 'Gerente' , 'Desarrollador' , 'Gerente' , 'Analista', None],
    'FechaIngreso': ['2021-01-15' , '2020/03/12' , '2022-07-01' , '2021/12/01' , None, '2020-03-12']
}

df = pd.DataFrame(data)
print("Información completa:")
print(df)

# 1.	Identificar y contar los valores faltantes en cada columna.
valores_faltantes = df.isnull().sum()
print("\nValores faltantes por columna:")
print(valores_faltantes)

# Reemplazar 'NaN' en 'Edad' por la media de edades
df['Edad'] = df['Edad'].fillna(df['Edad'].mean())
print("\nTabla con valores de edad inválidos reemplazados por la media:")
print(df)

# 2.	Verificar el formato de la columna 'Salario' para asegurar que todos los valores sean numéricos.
salarios_incorrectos = df[~df['Salario'].str.replace('[^0-9]', '', regex=True).fillna('').str.isdigit()]

# Reemplazar el salario_incorrecto por la media
index = salarios_incorrectos.index
df.loc[index, 'Salario'] = None
df['Salario'] = df['Salario'].astype(np.float64) # Puede usarse también .astype(int)
df['Salario'] = df['Salario'].fillna(df['Salario'].mean())
print('\nTabla con salarios numéricos:')
print(df)

# 3.	Validar y estandarizar el formato de la columna 'Fecha Ingreso' a YYYY-MM-DD.
df['FechaIngreso'] = df['FechaIngreso'].str.replace('/', '-')
df['FechaIngreso'] = pd.to_datetime(df['FechaIngreso'], errors='coerce', format='%Y-%m-%d')
print("\nDatos después de estandarizar 'FechaIngreso':")
print(df)

# 4.	Verificar que no haya valores faltantes en la columna "Cargo". Reemplazar los valores faltantes por equivalente en 'Salario'
# Reemplazar los valores faltantes en 'Cargo' buscando registros con el mismo Salario
for i, row in df[df['Cargo'].isnull()].iterrows():
    # Buscar un registro con el mismo Salario y un Cargo no nulo
    salario = row['Salario']
    posible_cargo = df[(df['Salario'] == salario) & (df['Cargo'].notnull())]['Cargo']

    # Si se encuentra un posible cargo, reemplazar el valor faltante
    if not posible_cargo.empty:
        df.at[i, 'Cargo'] = posible_cargo.iloc[0]

print("\nTabla después de reemplazar valores faltantes en 'Cargo':")
print(df)

Información completa:
   Nombre  Edad     Salario          Cargo FechaIngreso
0    Juan  28.0        3000       Analista   2021-01-15
1     Ana   NaN        4000        Gerente   2020/03/12
2   Pedro  40.0        4500  Desarrollador   2022-07-01
3   María  45.0  cuatro mil        Gerente   2021/12/01
4    Luis  38.0        5000       Analista         None
5  Carla   34.0        4000           None   2020-03-12

Valores faltantes por columna:
Nombre          0
Edad            1
Salario         0
Cargo           1
FechaIngreso    1
dtype: int64

Tabla con valores de edad inválidos reemplazados por la media:
   Nombre  Edad     Salario          Cargo FechaIngreso
0    Juan  28.0        3000       Analista   2021-01-15
1     Ana  37.0        4000        Gerente   2020/03/12
2   Pedro  40.0        4500  Desarrollador   2022-07-01
3   María  45.0  cuatro mil        Gerente   2021/12/01
4    Luis  38.0        5000       Analista         None
5  Carla   34.0        4000           None   2020-03-12

Tabla con salarios numéricos:
   Nombre  Edad  Salario          Cargo FechaIngreso
0    Juan  28.0   3000.0       Analista   2021-01-15
1     Ana  37.0   4000.0        Gerente   2020/03/12
2   Pedro  40.0   4500.0  Desarrollador   2022-07-01
3   María  45.0   4100.0        Gerente   2021/12/01
4    Luis  38.0   5000.0       Analista         None
5  Carla   34.0   4000.0           None   2020-03-12

Datos después de estandarizar 'FechaIngreso':
   Nombre  Edad  Salario          Cargo FechaIngreso
0    Juan  28.0   3000.0       Analista   2021-01-15
1     Ana  37.0   4000.0        Gerente   2020-03-12
2   Pedro  40.0   4500.0  Desarrollador   2022-07-01
3   María  45.0   4100.0        Gerente   2021-12-01
4    Luis  38.0   5000.0       Analista          NaT
5  Carla   34.0   4000.0           None   2020-03-12

Tabla después de reemplazar valores faltantes en 'Cargo':
   Nombre  Edad  Salario          Cargo FechaIngreso
0    Juan  28.0   3000.0       Analista   2021-01-15
1     Ana  37.0   4000.0        Gerente   2020-03-12
2   Pedro  40.0   4500.0  Desarrollador   2022-07-01
3   María  45.0   4100.0        Gerente   2021-12-01
4    Luis  38.0   5000.0       Analista          NaT
5  Carla   34.0   4000.0        Gerente   2020-03-12